defaults: &defaults
  access_key_id: "xxxx"
  secret_access_key: "zzzz"
  region: "eu-west-1"

development:
  <<: *defaults
  bucket: "rails_app_development"
  existing_remote_files: keep

test:
  <<: *defaults
  bucket: "rails_app_test"
  existing_remote_files: keep

production:
  <<: *defaults
  bucket: "rails_app_production"
  existing_remote_files: delete
